using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace Core.AI.Models;

/// <summary>
/// Represents the response from an AI provider, including result and any executed function.
/// </summary>
public class AIResponse
{
    /// <summary>
    /// The main text content generated by the AI.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    /// <summary>
    /// Indicates whether a function call was executed.
    /// </summary>
    public bool FunctionExecuted { get; set; }

    /// <summary>
    /// If a function was executed, this holds its name.
    /// </summary>
    public string? FunctionName { get; set; }

    /// <summary>
    /// If a function was executed, this holds its result (serialized object).
    /// </summary>
    public object? FunctionResult { get; set; }
}